CREATE TABLE IF NOT EXISTS stocks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    displayName TEXT NOT NULL,
    symbol TEXT UNIQUE NOT NULL,
    currentPrice REAL,
    industry TEXT,
    sector TEXT,
    fullExchangeName TEXT,
    region TEXT,
    market TEXT,
    totalRevenue INTEGER,
    totalCash INTEGER,
    totalDebt INTEGER,
    overallRisk TEXT,
    maxAge INTEGER,
    volume INTEGER,
    averageDailyVolume3Month INTEGER,
    sharesOutstanding INTEGER,
    trailingPE REAL,
    forwardPE REAL,
    lastFiscalYearEnd TEXT,
    averageVolume INTEGER,
    marketCap INTEGER,
    sharesShort INTEGER,
    grossMargins REAL,
    fiftyDayAverageChange REAL,
    fiftyTwoWeekChangePercent REAL
);
