INSERT INTO stocks (
    displayName,
    symbol,
    currentPrice,
    industry,
    sector,
    fullExchangeName,
    region,
    market,
    totalRevenue,
    totalCash,
    totalDebt,
    overallRisk,
    maxAge,
    volume,
    averageDailyVolume3Month,
    sharesOutstanding,
    trailingPE,
    forwardPE,
    lastFiscalYearEnd,
    averageVolume,
    marketCap,
    sharesShort,
    grossMargins,
    fiftyDayAverageChange,
    fiftyTwoWeekChangePercent
)
VALUES (
    json_extract(:json, '$.displayName'),
    json_extract(:json, '$.symbol'),
    json_extract(:json, '$.currentPrice'),
    json_extract(:json, '$.industry'),
    json_extract(:json, '$.sector'),
    json_extract(:json, '$.fullExchangeName'),
    json_extract(:json, '$.region'),
    json_extract(:json, '$.market'),
    json_extract(:json, '$.totalRevenue'),
    json_extract(:json, '$.totalCash'),
    json_extract(:json, '$.totalDebt'),
    json_extract(:json, '$.overallRisk'),
    json_extract(:json, '$.maxAge'),
    json_extract(:json, '$.volume'),
    json_extract(:json, '$.averageDailyVolume3Month'),
    json_extract(:json, '$.sharesOutstanding'),
    json_extract(:json, '$.trailingPE'),
    json_extract(:json, '$.forwardPE'),
    json_extract(:json, '$.lastFiscalYearEnd'),
    json_extract(:json, '$.averageVolume'),
    json_extract(:json, '$.marketCap'),
    json_extract(:json, '$.sharesShort'),
    json_extract(:json, '$.grossMargins'),
    json_extract(:json, '$.fiftyDayAverageChange'),
    json_extract(:json, '$.fiftyTwoWeekChangePercent')
);
